notifications:
  email: false
rvm:
  - 1.8.7
  - 1.9.3
  - jruby
before_script:
  - git submodule update --init
  - mkdir .akephalos
  - mkdir .akephalos/2.9
  - cp -r vendor/html-unit/ .akephalos/2.9/
script: "bundle exec rspec spec -f p"
